### ISSUE TITLE
Awersome work. But have questions about Lcm and Lora

### ISSUE THREAD

**Issue by SolicTous** [cpuimage/minSDTF#1]
I am trying to make manual run image_to_image, but instead of image with boy some enhansed getting 'flowers' if active_lcm is False and some bad if active_lcm is True. What's wrong in my way?
![out](https://github.com/cpuimage/minSDTF/assets/52211516/9fbd8eac-2d39-4690-87f7-d49a131493ed)

Models are loaded without error or warnings

```
model = StableDiffusion(img_height=512, img_width=512, jit_compile=True,
                        unet_ckpt=r"....\SimianLuoDreamshaper_v7\unet\diffusion_pytorch_model.safetensors",
                        text_encoder_ckpt=r"....\runwaymSD_v1-5\text_encoder\model.safetensors",
                        vae_ckpt=r"....\runwaymSD_v1-5\vae\diffusion_pytorch_model.safetensors",
                        lora_path=r"....\lora\lora.safetensors")

img = model.image_to_image(
    prompt = "natural colors, realistic, 8k",
    reference_image=r"D:\Datasets\ART\SimpleArt\021.jpg",
    unconditional_guidance_scale=7.5,
    guidance_rescale=0.7,
    seed=1,
    reference_image_strength=0.8,
    num_steps=4,
)
Image.fromarray(img[0]).save("out.jpg")
```

just example from running my pipeline. It's have to be some like this.
![021](https://github.com/cpuimage/minSDTF/assets/52211516/6720945a-454a-469e-8f66-9fac13945672)

And some one more question. t_emb_dim is 320, but in my pytorch/onnx pipeline is 256, so i can't use tensorflow model in my pipeline. There are 4 inputs for unet without using control_net
'sample', 'timestep', 'timestep_cond', 'encoder_hidden_states'

but in your unet 3 inputs instead of 4,
'latent', 't_emb', 'unconditional_context'

I want to run SD_LCM_Lora with TF, so see your way is fantastic, but do not understand above differences and why getting flower instead of art closed to input_image. It's really cool convert from PT to TF without using ONNX step. You made it manually, so hard.

**Comment by cpuimage** [comment]
@SolicTous hi,since I am not a native English speaker, as much as I can understand the questions you are asking give some thoughts:
1.flowers issues try use guidance_rescale=0.0
2.control_net issues check here:
https://github.com/cpuimage/minSDTF/blob/main/stable_diffusion/stable_diffusion.py#L447
3.t_emb_dim issues check here:
https://github.com/cpuimage/minSDTF/blob/main/stable_diffusion/stable_diffusion.py#L543
