### ISSUE TITLE
How to run LCM-Lora Dreamshaper?

### ISSUE THREAD

**Issue by SolicTous** [cpuimage/minSDTF#2]
Can you provide full example for running 4-6steps img2img LCM-Lora stable diffusion?
I'm trying to make, but can't archieve normal result.

My load looks like:
```
model = StableDiffusion(img_height=512, img_width=512, jit_compile=True, active_lcm = True,
                        unet_ckpt=r"...\LykonDreamshaper_v8\DreamShaper8_LCM.safetensors",
                        text_encoder_ckpt=r"...\SimianLuoDreamshaper_v7\text_encoder\model.safetensors",
                        vae_ckpt=r"...\runwaymSD_v1-5\vae\diffusion_pytorch_model.safetensors",
                        lora_path=r"...\lora\lora.safetensors")
```

I maked active_lcm manual in StableDiffusion class to be sure that it's active.

And img2img run look like that, even changing parameters does not help, the result is different.
```
img = model.image_to_image(
    prompt = "natural colors, realistic, 8k",
    reference_image="000.png",
    unconditional_guidance_scale=0,
    guidance_rescale=0,
    seed=0,
    reference_image_strength=0.8,
    num_steps=4,)
cv2.imshow('_', cv2.cvtColor(img[0], cv2.COLOR_RGB2BGR))
cv2.waitKey(0)
```

![image](https://github.com/cpuimage/minSDTF/assets/52211516/86d0f50d-e620-4f87-a8f7-a8d8bf0b2606)

But it have to like that (it's from pytorch inference)
![image](https://github.com/cpuimage/minSDTF/assets/52211516/7258c3e5-52e8-419a-a61d-41f2ea4018ea)

**Comment by cpuimage** [comment]
@SolicTous It's like a problem with passing  “active_lcm” parameter. check this https://github.com/cpuimage/minSDTF/commit/4552b817bbfdbcb6f8e5af1f71cc128f52b9d50a

**Comment by SolicTous** [comment]
@cpuimage 
As I said above - maked it's already. Even with active_lcm, and lora loaded I can't archieve normal result.

**Comment by cpuimage** [comment]
@SolicTous Pack up your code and all the model weights and send it to me (gaozhihan@vip.qq.com) using Google Netflix or something and I'll check what's wrong.

**Comment by cpuimage** [comment]
@SolicTous 
It looks like you're trying to generate an image using ControlNet, but you're only using img2img and you need to load the ControlNet model
```python 
import cv2
import numpy as np
from PIL import Image
 
from stable_diffusion.stable_diffusion import StableDiffusion

model = StableDiffusion(img_height=512, img_width=512, jit_compile=True, active_lcm=True,
                        unet_ckpt="./dreamshaper_v7_unet.safetensors",
                        text_encoder_ckpt="./dreamshaper_v7_text_encoder.safetensors",
                        vae_ckpt="./runwaymSD_v1-5_vae.safetensors",
                        lora_path="./lora.safetensors", controlnet_path="./control_sd15_canny.pth")   
# using control_sd15_canny
# download from: 
# https://huggingface.co/lllyasviel/ControlNet/blob/main/models/control_sd15_canny.pth

# preprocessing with canny 
control_net_image = "000.png"
image = Image.open(control_net_image).convert("RGB")
image = np.array(image)
canny = cv2.Canny(image, 100, 200)
canny = np.expand_dims(canny, axis=-1)
canny = np.concatenate([canny, canny, canny], axis=2)

img = model.image_to_image(
    prompt="natural colors, realistic, 8k",
    reference_image="000.png",  # for img2img
    unconditional_guidance_scale=0,
    guidance_rescale=0,
    seed=0,
    control_net_image=canny.astype(np.float32), # pay attention here 
    reference_image_strength=0.8,
    num_steps=4, )
Image.fromarray(img[0]).save("out.jpg")

cv2.imshow('_', cv2.cvtColor(img[0], cv2.COLOR_RGB2BGR))
cv2.waitKey(0)
```
ControlNet related code does have a part of the logic is not well thought out, waiting for some time to improve it.

**Comment by SolicTous** [comment]
In the pytorch example above I do not used control net and any other adapters, only LCM and Lora weights.
So when i'm use pytorch manual pipeline -> Unet have one input more for **guidance scale paramenter**, but no ControlNet:
sample
timestep
**timestep_cond** (have to be added, but can work without it)
encoder_hidden_states

**Comment by cpuimage** [comment]
@SolicTous 
I still don't understand exactly what kind of thing you're trying to do, what exactly does the pytorch code implementation look like?
If you can articulate the claim, I'll take the time to look it over for you.

**Comment by SolicTous** [comment]
@cpuimage
Really thank you for help. Control_Net is good for getting better result. It's awersome.
And it work with that. Launched with control net:
![изображение](https://github.com/cpuimage/minSDTF/assets/52211516/c5131358-b27b-470a-8701-134a82b05c2d)

Sorry for bad formulation, I will try to describe correctly.

My first and main question is how to run img2img to archieve result that showen above **without control_net**
I have not used control_net before your advice. But as i can see even without canny it can be normal result in pytorch.
https://huggingface.co/latent-consistency/lcm-lora-sdv1-5 (Image-to-Image, LCM-LoRA.)
**When I look what happens inside of pipe there are no control net used unless it's not active manually.**

My pipeline is a copy from this way:
https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/latent_consistency_models/pipeline_latent_consistency_img2img.py

The second question is about inputs of Unet, inside goal pipeline there are 4 inputs instead of 3:
`sample, timestep, timestep_cond, encoder_hidden_states`
Where `timestep_cond` = `w_embedding`:
```  
    w = torch.tensor(guidance_scale - 1).repeat(bs)
    w_embedding = self.get_guidance_scale_embedding(w, embedding_dim=256).to(device='cpu', dtype=latents.dtype)
```
 guidance_scale is degree how the image influences the result
 (like strength changes influence of prompt)
 
```
    def get_guidance_scale_embedding(self, w, embedding_dim=512, dtype=torch.float32):
        assert len(w.shape) == 1
        w = w * 1000.0
        half_dim = embedding_dim // 2
        emb = torch.log(torch.tensor(10000.0)) / (half_dim - 1)
        emb = torch.exp(torch.arange(half_dim, dtype=dtype) * -emb)
        emb = w.to(dtype)[:, None] * emb[None, :]
        emb = torch.cat([torch.sin(emb), torch.cos(emb)], dim=1)
        if embedding_dim % 2 == 1:  # zero pad
            emb = torch.nn.functional.pad(emb, (0, 1))
        assert emb.shape == (w.shape[0], embedding_dim)
        return emb
```

```
model_pred = unet(latents, t, timestep_cond=w_embedding, encoder_hidden_states=prompt_embeds)
```

May be adding guildance scale and canny together will be very nice combo for img2img lcm lora best results.

**Comment by cpuimage** [comment]
@SolicTous    
I also have some confusion about the output.
It looks like there is a computational or compatibility issue with loading the lora file for lcm, and after merging the lcm weights into unet, it would be more appropriate to load unet directly rather than using the lora file.

get_guidance_scale_embedding is a special case implementation, and I haven't done some compatibility testing on its implementation details. 

step 1:
```
wget https://huggingface.co/Lykon/dreamshaper-8-lcm/resolve/main/DreamShaper8_LCM.safetensors?download=true -O DreamShaper8_LCM.safetensors
```
step 2:
```python
import cv2
import numpy as np
from PIL import Image
 
from stable_diffusion.stable_diffusion import StableDiffusion

model = StableDiffusion(img_height=512, img_width=512, jit_compile=True, active_lcm=True,
                        unet_ckpt="./DreamShaper8_LCM.safetensors",
                        text_encoder_ckpt="./dreamshaper_v7_text_encoder.safetensors",
                        vae_ckpt="./runwaymSD_v1-5_vae.safetensors",
                      #  lora_path="./lora.safetensors",
                        controlnet_path="./control_sd15_canny.pth")   
# using control_sd15_canny
# download from: 
# https://huggingface.co/lllyasviel/ControlNet/blob/main/models/control_sd15_canny.pth

# preprocessing with canny 
control_net_image = "000.png"
image = Image.open(control_net_image).convert("RGB")
image = np.array(image)
canny = cv2.Canny(image, 100, 200)
canny = np.expand_dims(canny, axis=-1)
canny = np.concatenate([canny, canny, canny], axis=2)

img = model.image_to_image(
    prompt="natural colors, realistic, 8k",
    reference_image="000.png",  # for img2img
    unconditional_guidance_scale=0,
    guidance_rescale=0,
    seed=-1, # using -1 here
    control_net_image=canny.astype(np.float32), 
    reference_image_strength=0.8,
    num_steps=4, )
Image.fromarray(img[0]).save("out.jpg")

cv2.imshow('_', cv2.cvtColor(img[0], cv2.COLOR_RGB2BGR))
cv2.waitKey(0)
```

**Comment by SolicTous** [comment]
So, with canny control_net it works,
but without them not for a while (have to be).

I also will try to understand where the way differ to pytorch pipe. I want run without control_net and canny with similar result.
